# Start Lab 5
# Program to find the sum and calculate the average of ‘n’ numbers in a list. The user enters the number ‘n’ and the ‘n’ numbers that form the list.
n = input("Enter the numbers to calculate: ")
list = n.split()
print(list)
sum = 0
for num in list:
    sum = sum + int(num)
print("The sum of the numbers in the list is ", sum)
print("The average of the numbers in the list is ", sum/len(list))

# Write a program where the user enters the number of elements in a list ‘n’ and those ‘n’ numbers that form the list. The user also enters a number ‘m’ by which all the elements of the list are multiplied and printed. You must print both the list before multiplying and the list after multiplied by the number ‘m’.
n = input("Enter the numbers to calculate: ")
m = int(input("Enter the number to multiply by: "))
list = n.split()
print(list)
for num in list:
    num = int(num) * m
    print(num)

# Given the initial statements
str1 = "spam"
str2 = "ni !"
# Show the result of evaluating each of the following string expressions.
# Print the result of each expression on a separate line.
print("The Knights who say , " + str2 )
print("3 * str1 + 2 * str2")
print(str1 [1])
print(str1 [1 : 3] )
print(str1 [2] + str2 [ : 2] )
print(str1 + str2 [ -1] )
print(str1.upper() )
print(str2.upper() * 3 )

# Show the output generated by each of the following program fragments:
for ch in " aardvark":
    print(ch)

for w in " Now is the winter of our discontent . . . ".split():
    print(w)

for w in "Mississippi ".split(" i "):
    print(w, end=" ")

msg = " "

for s in " secret ".split(" e "):
    msg = msg + s

print(msg)

msg = " "

for ch in " secret ":
    msg = msg + chr(ord(ch) + 1)

print(msg)

# Use a dictionary to store information about a person you know. Store their first name, last name, age, and the city in which they live. You should have keys such as first_name, last_name, age, and city. Print each piece of information stored in your dictionary. (
import pprint
import json
dict = {"first_name": "Dakota", "last_name": "Street", "age": 19, "city": "Miami"}
better = json.dumps(dict, indent=4)
print(better)

# Use these words as the keys in your glossary, and store their meanings as values.
# Print each word and its meaning as neatly formatted output
import pprint
import json
dict = {"Array": "A collection of data items of the same type stored in contiguous memory locations", "Index": "An integer value that is used to access an element of an array", "List": "A collection of data items of the same type stored in contiguous memory locations", "Dictionary": "A collection of data items of the same type stored in contiguous memory locations", "String": "A collection of data items of the same type stored in contiguous memory locations", "Stacks": "A collection of data items of the same type stored in contiguous memory locations", "Queues": "A collection of data items of the same type stored in contiguous memory locations", "Graph": "A collection of data items of the same type stored in contiguous memory locations", "Queues": "A list that adds data to one end and deletes data from the other end.", "Stacks": "A list that adds data to one end and deletes data from the same end."}
mew = json.dumps(dict, indent=4)
print(mew)

# End Lab 5